//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        public string codalu { get; set; }
        public string nomalu { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string codcar { get; set; }
        public Nullable<System.DateTime> fecha_ins { get; set; }
        public string estado { get; set; }
    }
}
