//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTAS
    {
        public string semestre { get; set; }
        public string codalu { get; set; }
        public string codcur { get; set; }
        public Nullable<float> pp { get; set; }
        public Nullable<float> pt { get; set; }
        public Nullable<float> ex { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fec_mat { get; set; }
        public Nullable<System.DateTime> fech_nota { get; set; }
    }
}
